### PR TITLE
✨ Restructure code to have better readability

### LINKED ISSUE #37: Restructure code base to have better redability
***Goals***
- The goal is to have clean and less indented code and a good package-based structure for future easy debugging.

***Non-Goals/Future Work***
1. Non-Goal 1
1. Non-Goal 2

**User Story**

As a [developer/user/operator] I would like to [high level description] for [reasons]

**Detailed Description**

[A clear and concise description of what you want to happen.]

/kind proposal

### PR DESCRIPTION
**Pull request by aniruddha2000**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #37 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Comment by guettli** [comment]
@aniruddha2000 the heading of the PR does not fit to the content. The PR adds the new content based hasing. Please add this to the title and the description.

**Comment by aniruddha2000** [comment]
done

**Comment by aniruddha2000** [comment]
@guettli please review it again, I've removed the **git hash and clusterstack hash** from this PR and will add a follow up PR after this

**Review by janiskemper — APPROVED** [review]
approving this to not block further PRs. If bugs exist, we can fix them later before we release

**Pull request merged**
